"""empty message

Revision ID: 0f87e8f45ce0
Revises: 
Create Date: 2020-05-23 22:48:17.570273

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0f87e8f45ce0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=256), nullable=False),
                    sa.Column('full_name', sa.String(length=512),
                              nullable=False),
                    sa.Column('date_of_birth', sa.Date(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('movies',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=256), nullable=False),
                    sa.Column('release_year', sa.Integer(), nullable=False),
                    sa.Column('duration', sa.Integer(), nullable=False),
                    sa.Column('imdb_rating', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('actor_in_movie',
                    sa.Column('actor_id', sa.Integer(), nullable=False),
                    sa.Column('movie_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
                    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
                    sa.PrimaryKeyConstraint('actor_id', 'movie_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actor_in_movie')
    op.drop_table('movies')
    op.drop_table('actors')
    # ### end Alembic commands ###
